Ajout d'une monotone de demande
CEA-Liten/HeatPro-App pull request #2
Opened 2024-08-05 09:42 UTC by Margaux-Ccd

Ajout d'un _expander_ qui donne la monotone de chaleur et changement de couleur des zones des graphiques donnant la _Heating Season_.

2024-08-05 11:58 UTC, RobinsonBeaucour requested changes
Bon début !

2024-08-05 11:58 UTC, RobinsonBeaucour commented on backend/monotone.py
> +                    x = [i for i in range(0,24*365)],
Cette ligne est à revoir pour que le graphique s'adapte à des périodes différentes d'une période de 1 an. 
En plus, ce serait mieux que ce soit en pourcentage plutôt qu'en nombre d'heure.

2024-08-06 12:55 UTC, Margaux-Ccd commented
> Il y a un problème dans ta monotone de charge néanmoins ... ![image](https://private-user-images.githubusercontent.com/45032111/355109750-a9dc6f6c-8108-47b8-9064-a61a004d8e5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDkwMjcsIm5iZiI6MTcyMjk0ODcyNywicGF0aCI6Ii80NTAzMjExMS8zNTUxMDk3NTAtYTlkYzZmNmMtODEwOC00N2I4LTkwNjQtYTYxYTAwNGQ4ZTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEyNTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0N2MwYjg3ZGEzMjc1MDNlOTQ4NTVlOWI0YzliMzAyYWQzMzA0MzI4NTRmYmMzMzQwZThiYmM0MzRkOTc2ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NUcidym0J9AwQnHSSFRMAUzYdnpTqqCuAU2bqcxg3qM)

résolu dans 213649cc5b5d93d98d52871a16fb34b3782c3fa9

2024-08-06 14:15 UTC, RobinsonBeaucour requested changes

2024-08-06 14:15 UTC, RobinsonBeaucour commented on backend/monotone.py
La création de ce fichier n'est pas nécessaire. Déplace la fonction `plot_monotone` dans `visualisation.py`.

2024-08-06 14:15 UTC, RobinsonBeaucour commented on app.py
> +with st.expander("Heat monotone",expanded=True):
Je préfère que le graphique soit dans l'expander précédent. En tout cas pour ce type de graphique c'est plutôt logique que les deux soient dans le même expander. Par contre pour d'autres graphiques ça peut être en effet une bonne idée d'avoir un expander séparé.

2024-08-07 09:26 UTC, RobinsonBeaucour commented
@Margaux-Ccd J'ai l'impression que tu pourrais essayer de t'occuper de #3

2024-08-08 08:06 UTC, RobinsonBeaucour requested changes

2024-08-08 08:06 UTC, RobinsonBeaucour commented on backend/visualisation.py
> +def plot_energy_temp(district_heating: DistrictHeatingLoad) -> go.Figure:
Change le nom pour `plot_demand_vs_outside_temperature`, il faut pas forcément se gêner à faire des noms long mais explicites en programmation c'est un gain pour plus tard lorsque le projet et plus complexe et que des ambiguïtés peuvent apparaître. 

Du coup, il faudrait avoir deux nuages de points (pour HS et pour NHS). pour la HS il faudrait que ce soit la même couleur que le rectangle de `plot_generated_load`.

2024-08-08 08:06 UTC, RobinsonBeaucour commented on backend/visualisation.py
> +                layout_hovermode='x unified',
Pour ce graphique là, on peut enlever le layout_hovermode

2024-08-09 07:06 UTC, Margaux-Ccd commented on backend/visualisation.py
> +def plot_energy_temp(district_heating: DistrictHeatingLoad) -> go.Figure:
Le nom a été changé dans fb13b517adeba1c4915694435395984692bbbe7e.

2024-08-09 07:07 UTC, Margaux-Ccd commented on app.py
> +with st.expander("Heat monotone",expanded=True):
L'ordre des graphiques a été changé dans 3accc3861230bebff8de886732f875a81bfd8bf7

2024-08-09 07:55 UTC, RobinsonBeaucour approved these changes

2024-08-09 07:57 UTC, merged